name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - run: | 
         some_response=$(curl google.com)
         echo response_output=$some_response >> $GITHUB_OUTPUT
        id: some-request
      - run: |
         echo "Response is: ${{ steps.some-request.outputs.response_output }}"
         
      - name: Get Some output data
        id: run_tests
        run: |
          echo "mix-format=$(echo "something")\n" >> $GITHUB_OUTPUT
      - name: Update Pull Request
        uses: actions/github-script@v6
        env:
          # PLAN: "terraform\n${{steps.plan.outputs.stdout}}"
          PLAN: "terraform\n${{join(steps.some-request.outputs.*, '\n')}}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `${process.env.PLAN}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Slack Notification
        run: |
          echo "SLACK_WEBHOOK = $SLACK_MESSAGE"
          echo "SLACK_TITLE = $SLACK_TITLE"
          echo "GITHUB_OUT = $GITHUB_OUT"
        env:
          SLACK_MESSAGE: ${{join(steps.run_tests.outputs.*, '\n')}}
          SLACK_TITLE: ${{steps.run_tests.outputs.stdout}}
          GITHUB_OUT: ${{steps.run_tests.outputs.mix-format}}

