name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: Get Some output data
        id: run_tests
        run: |
          echo "mix-format--check-formatted=$(echo TT)\n" >> $GITHUB_OUTPUT

      - name: Slack Notification
        run: |
          echo "SLACK_WEBHOOK = $SLACK_MESSAGE"
        env:
          SLACK_MESSAGE: ${{join(steps.run_tests.outputs.*, '\n')}}
          SLACK_TITLE: CI Test Suite
